import { env } from '../config/env.js';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
// import creds from './config/client_secret.json';

export async function accessSpreadsheet() {
    const SCOPES = [
        'https://www.googleapis.com/auth/spreadsheets'
    ];

    // env var here are copied from service account credentials generated by google
    const serviceAccountAuth = new JWT({
        email: env.googleClientEmail,
        key: env.googlePrivateKey,
        scopes: SCOPES // explicitily declaring what this client is allowed to do (req permission to access the spreadsheets scope)
    });

    // when passing the second argument, we plug the authentication clent into the spreadhseet
    // library so every future req is automatically signed
    const doc = new GoogleSpreadsheet(env.googleSheetID, serviceAccountAuth);

    //fetch data
    await doc.loadInfo();
    console.log(doc.title)

    // const sheet = doc.sheetByIndex[0];
    // const rows = await sheet.getRows();
    // console.log(rows)
}


accessSpreadsheet();